# create a few users
# buggy - it should probably use the password_hash, Password.create from bcrypt
  User.create(username: "Luffy", email: "luffy@onepiece.com", password: "jjj")
  User.create(username: "Zoro", email: "zoro@onepiece.com", password: "jjj")
  User.create(username: "Nami", email: "nami@onepiece.com", password: "jjj")

# create bands
  Band.create(name: "Beirut")
  Band.create(name: "Chet Faker")
  Band.create(name: "Grimes")
  Band.create(name: "The National")
  Band.create(name: "ODESZA")
  Band.create(name: "The Head And The Heart")
  Band.create(name: "Lo-Fang")
  Band.create(name: "Sufjan Stevens")
  Band.create(name: "Kings Of Convenience")
  Band.create(name: "Jose Gonzalez")
  Band.create(name: "Wu-Tang Clan")
  Band.create(name: "Bon Iver")
  Band.create(name: "Drake")
  Band.create(name: "The Weeknd")
  Band.create(name: "Tennis")
  Band.create(name: "Haim")
  Band.create(name: "Broods")

#create events

  Concert.create(venue: "Greek Theatre", city: "Berkeley, CA" , date: "10/10/2015", band_id: 1)
  Concert.create(venue: "Bearsville Theater", city: "Woodstock, NY" , date: "2015/06/19", band_id: 1)
  Concert.create(venue: "Waterfront Park", city: "Portland, OR" , date: "2015/08/23", band_id: 1)
  Concert.create(venue: "Zenith", city: "Paris, France" , date: "2015/09/22", band_id: 1)
  Concert.create(venue: "Paramount Theatre", city: "Seattle, WA" , date: "2015/10/13", band_id: 1)
  Concert.create(venue: "Eaux Fairgrounds", city: "Eau Claire, WI" , date: "2015/07/17", band_id: 4)
  Concert.create(venue: "Treasure Island", city: "San Francisco, CA" , date: "2015/10/17", band_id: 4)
  Concert.create(venue: "Flow Festival Grounds", city: "Ljubljana, Slovenia" , date: "2015/06/26", band_id: 10)
  Concert.create(venue: "Golden Gate Park", city: "San Francisco, CA" , date: "2015/08/07", band_id: 5)
  Concert.create(venue: "Fairplex", city: "Pomona, CA" , date: "2015/08/01", band_id: 5)
  Concert.create(venue: "Somerset Ampitheater", city: "Somerset, WI" , date: "2015/09/01", band_id: 5)
  Concert.create(venue: "Aaron's Amphitheatre at Lakewood", city: "Atlanta, GA" , date: "2015/06/16", band_id: 3)
  Concert.create(venue: "Coral Sky Amphitheatre", city: "West Palm Beach, FL" , date: "2015/06/19", band_id: 3)
  Concert.create(venue: "TivoliVredenburg", city: "Utrecht, Netherlands" , date: "2015/06/17", band_id: 2)
  Concert.create(venue: "Hutchinson Field, Grant Park", city: "Chicago, IL" , date: "2015/09/02", band_id: 2)
